import swaggerAutogen from 'swagger-autogen';
const doc = {
	info: {
		title: 'Crypto Trade Platforms APIs',
		description:
			'a set of backend APIs to retrieve the orderbook, current price, and candles \nfrom various cryptocurrency exchanges such as \nBinance, MEXC, Gate.io, KuCoin, and AscendEX.',
	},
	host: 'localhost:9000',
};

const outputFile = './swagger-output.json';
const routes = ['../../api/index.js'];

swaggerAutogen(outputFile, routes, doc).then(() => {
	console.log('Docs Autogenerated');
	console.log('Docs available at http://localhost:9000/api-docs');
});
